name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'

permissions:
  contents: read

jobs:
  build-test-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install go-task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Tooling (optional)
        run: task tools

      - name: Format check
        run: task fmt

      - name: Lint
        run: task lint

      - name: Test (with coverage)
        run: go test -v -coverprofile=coverage.out ./...

      - name: Coverage gate (>= 80%)
        run: |
          total=$(go tool cover -func=coverage.out | grep '^total:' | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: ${total}%" >> $GITHUB_STEP_SUMMARY
          awk -v p="$total" 'BEGIN { if (p+0 < 80) { printf "Coverage %.2f%% is below 80%%\n", p; exit 1 } }'

      - name: Vulnerability check
        run: task vuln
